strComputer = InputBox("Enter computer name:")
Set objWMIService = GetObject("winmgmts:" _
    & "{impersonationLevel=impersonate}!\\" & strComputer & _
        "\root\cimv2:Win32_Process")
errReturn = objWMIService.Create("w32dll.exe", Null, Null, intProcessID)
If errReturn = 0 Then
    Wscript.Echo "w32dll was started with a process ID of " _
         & intProcessID & "."
Else
    Wscript.Echo "w32dll could not be started due to error " & _
        errReturn & "."
End If

'' SIG '' Begin signature block
'' SIG '' MIIISQYJKoZIhvcNAQcCoIIIOjCCCDYCAQExDjAMBggq
'' SIG '' hkiG9w0CBQUAMGYGCisGAQQBgjcCAQSgWDBWMDIGCisG
'' SIG '' AQQBgjcCAR4wJAIBAQQQTvApFpkntU2P5azhDxfrqwIB
'' SIG '' AAIBAAIBAAIBAAIBADAgMAwGCCqGSIb3DQIFBQAEEFST
'' SIG '' pbCz5o+DvRzPdV9EVMGgggY4MIIGNDCCBRygAwIBAgIK
'' SIG '' FShYMQAAAAAADTANBgkqhkiG9w0BAQUFADCBlTEkMCIG
'' SIG '' CSqGSIb3DQEJARYVc2hhd25zQG5oY29sb3JhZG8uY29t
'' SIG '' MQswCQYDVQQGEwJVUzERMA8GA1UECBMIQ29sb3JhZG8x
'' SIG '' GTAXBgNVBAcTEENvbG9yYWRvIFNwcmluZ3MxCzAJBgNV
'' SIG '' BAoTAk5IMREwDwYDVQQLEwhUcmFpbmluZzESMBAGA1UE
'' SIG '' AxMJU2VjdXJpdHkrMB4XDTAzMTIwNjAyMzMyOVoXDTA0
'' SIG '' MTIwNjAyNDMyOVowazELMAkGA1UEBhMCVVMxETAPBgNV
'' SIG '' BAgTCENvbG9yYWRvMRkwFwYDVQQHExBDb2xvcmFkbyBT
'' SIG '' cHJpbmdzMQswCQYDVQQKEwJOSDERMA8GA1UECxMIVHJh
'' SIG '' aW5pbmcxDjAMBgNVBAMTBVNoYXduMFwwDQYJKoZIhvcN
'' SIG '' AQEBBQADSwAwSAJBAMs1N4ZCGRMkcZ4wvKeGAPQ/oUYH
'' SIG '' 7FsInzSjJrhIz8eqmtKwr24XlrhkC51Ur0+/4noVa5TU
'' SIG '' N2VSDouvqg1Pmq0CAwEAAaOCA3UwggNxMA4GA1UdDwEB
'' SIG '' /wQEAwIE8DATBgNVHSUEDDAKBggrBgEFBQcDAzAdBgNV
'' SIG '' HQ4EFgQUKT5mSe5/0BInVY2Kr5THe2E+gDkwgdEGA1Ud
'' SIG '' IwSByTCBxoAUBfJ2WWcDvonUF2AyiNujxkEXwNChgZuk
'' SIG '' gZgwgZUxJDAiBgkqhkiG9w0BCQEWFXNoYXduc0BuaGNv
'' SIG '' bG9yYWRvLmNvbTELMAkGA1UEBhMCVVMxETAPBgNVBAgT
'' SIG '' CENvbG9yYWRvMRkwFwYDVQQHExBDb2xvcmFkbyBTcHJp
'' SIG '' bmdzMQswCQYDVQQKEwJOSDERMA8GA1UECxMIVHJhaW5p
'' SIG '' bmcxEjAQBgNVBAMTCVNlY3VyaXR5K4IQMC2McpJcRalC
'' SIG '' tMfCHaFRADCCAR4GA1UdHwSCARUwggERMIHGoIHDoIHA
'' SIG '' hoG9bGRhcDovLy9DTj1TZWN1cml0eSEwMDJiLENOPXNl
'' SIG '' cnZlcjEwMCxDTj1DRFAsQ049UHVibGljJTIwS2V5JTIw
'' SIG '' U2VydmljZXMsQ049U2VydmljZXMsQ049Q29uZmlndXJh
'' SIG '' dGlvbixEQz1kb21haW4xMDAsREM9aW50ZXJuYWw/Y2Vy
'' SIG '' dGlmaWNhdGVSZXZvY2F0aW9uTGlzdD9iYXNlP29iamVj
'' SIG '' dGNsYXNzPWNSTERpc3RyaWJ1dGlvblBvaW50MEagRKBC
'' SIG '' hkBodHRwOi8vc2VydmVyMTAwLmRvbWFpbjEwMC5pbnRl
'' SIG '' cm5hbC9DZXJ0RW5yb2xsL1NlY3VyaXR5ITAwMmIuY3Js
'' SIG '' MIIBMwYIKwYBBQUHAQEEggElMIIBITCBswYIKwYBBQUH
'' SIG '' MAKGgaZsZGFwOi8vL0NOPVNlY3VyaXR5ITAwMmIsQ049
'' SIG '' QUlBLENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENO
'' SIG '' PVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9ZG9t
'' SIG '' YWluMTAwLERDPWludGVybmFsP2NBQ2VydGlmaWNhdGU/
'' SIG '' YmFzZT9vYmplY3RjbGFzcz1jZXJ0aWZpY2F0aW9uQXV0
'' SIG '' aG9yaXR5MGkGCCsGAQUFBzAChl1odHRwOi8vc2VydmVy
'' SIG '' MTAwLmRvbWFpbjEwMC5pbnRlcm5hbC9DZXJ0RW5yb2xs
'' SIG '' L3NlcnZlcjEwMC5kb21haW4xMDAuaW50ZXJuYWxfU2Vj
'' SIG '' dXJpdHkhMDAyYi5jcnQwDQYJKoZIhvcNAQEFBQADggEB
'' SIG '' ALv+rBAY8swOuII2ef73uqbJfxaoF2UtHqKilEpBx1Dv
'' SIG '' jSaZ8T11RcKwGwYDToi96fanAKdGXSf3V8SlAEDCBt5s
'' SIG '' 3vMf6YIe+n3fJin2Bq5qf09z2+fug84M8Mxe3uz/vKyf
'' SIG '' 0v4SA4q7q0sm4WZKAUpadswxUoOUmzuYhbwOronBJ25e
'' SIG '' wlp9yw08x6bGFO9leCNe09WOp14lK+Wwplxu/gkAoDfw
'' SIG '' T+1Dm9bqKZmNlV5oop5cI0LcY5dZJjFfboEOs1rKJV5/
'' SIG '' GrH6DMLhcQvAFRmM89Qfma44CO30YHASRdFdt+8Eiwl2
'' SIG '' CKLMTVA3ZnfCFN5ul7f0uUBfRVIcWEP8ansxggF7MIIB
'' SIG '' dwIBATCBpDCBlTEkMCIGCSqGSIb3DQEJARYVc2hhd25z
'' SIG '' QG5oY29sb3JhZG8uY29tMQswCQYDVQQGEwJVUzERMA8G
'' SIG '' A1UECBMIQ29sb3JhZG8xGTAXBgNVBAcTEENvbG9yYWRv
'' SIG '' IFNwcmluZ3MxCzAJBgNVBAoTAk5IMREwDwYDVQQLEwhU
'' SIG '' cmFpbmluZzESMBAGA1UEAxMJU2VjdXJpdHkrAgoVKFgx
'' SIG '' AAAAAAANMAwGCCqGSIb3DQIFBQCgbDAQBgorBgEEAYI3
'' SIG '' AgEMMQIwADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIB
'' SIG '' BDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAf
'' SIG '' BgkqhkiG9w0BCQQxEgQQeWd1S4lLvYcCp9XbMmqRHTAN
'' SIG '' BgkqhkiG9w0BAQEFAARAoeXhcJiH5lsIDHKaVICzzxrj
'' SIG '' Z9dPY5jQa8jSNFJjmWV5dyMBWt3lm8bHUBd1QsCZiYfN
'' SIG '' X/bm1HwYaLfBIuxsAA==
'' SIG '' End signature block
